### ISSUE TITLE
按照说明，未能成功运行文件

### ISSUE THREAD

**Issue by LR-Shur** [MANGO1234/AlphaStS#1]
我按照你的说明逐步运行，到了最后一步输出：
Seed: 163468314074864
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
        at com.alphaStS.Main.parseCommonArgs(Main.java:116)
        at com.alphaStS.Main.interactiveMode(Main.java:134)
        at com.alphaStS.Main.main(Main.java:46)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
       对不起，我是初学者，看不懂，chatgpt也未能指导我，我安装了java jdk和maven

**Comment by MANGO1234** [comment]
Sorry I haven't been on github for a while and miss this. Does your maven repo contain the jackson libraries?

**Comment by LR-Shur** [comment]
看来是并没有，我去看看jackson libraries
